import "./globals.css";
import "../../node_modules/bootstrap/dist/css/bootstrap.css";
import { ReduxProvider } from "./redux/provider";
import Footer from "../../components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning={true} lang="en">
      <div className="" style={{ minHeight: "100vh" }}>
        <ReduxProvider className="redux"> {children} </ReduxProvider>
        <Footer />
      </div>
    </html>
  );
}
