export const MEDICINE_ADD_REQUEST = 'MEDICINE_ADD_REQUEST'
export const MEDICINE_ADD_SUCCESS = 'MEDICINE_ADD_SUCCESS'
export const MEDICINE_ADD_FAIL = 'MEDICINE_ADD_FAIL'

export const MEDICINE_EDIT_REQUEST = 'MEDICINE_EDIT_REQUEST'
export const MEDICINE_EDIT_SUCCESS = 'MEDICINE_EDIT_SUCCESS'
export const MEDICINE_EDIT_FAIL = 'MEDICINE_EDIT_FAIL'

export const MEDICINE_DELETE_REQUEST = 'MEDICINE_DELETE_REQUEST'
export const MEDICINE_DELETE_SUCCESS = 'MEDICINE_DELETE_SUCCESS'
export const MEDICINE_DELETE_FAIL = 'MEDICINE_DELETE_FAIL'

export const MEDICINE_GET_BY_ID_REQUEST = 'MEDICINE_GET_BY_ID_REQUEST'
export const MEDICINE_GET_BY_ID_SUCCESS = 'MEDICINE_GET_BY_ID_SUCCESS'
export const MEDICINE_GET_BY_ID_FAIL = 'MEDICINE_GET_BY_ID_FAIL'

export const MEDICINE_GET_ALL_REQUEST = 'MEDICINE_GET_ALL_REQUEST'
export const MEDICINE_GET_ALL_SUCCESS = 'MEDICINE_GET_ALL_SUCCESS'
export const MEDICINE_GET_ALL_FAIL = 'MEDICINE_GET_ALL_FAIL'

export const MEDICINES_VIEW_SUCCESS = 'MEDICINES_VIEW_SUCCESS';
export const MEDICINES_VIEW_REQUEST = 'MEDICINES_VIEW_REQUEST';
export const MEDICINES_VIEW_FAIL = 'MEDICINES_VIEW_FAIL';