export const ORDER_DETAILS_SUCCESS ='ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_REQUEST ='ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_FAIL ='ORDER_DETAILS_FAIL';
export const ORDER_ADDRESSES_SUCCESS ='ORDER_ADDRESSES_SUCCESS';
export const ORDER_ADDRESSES_REQUEST ='ORDER_ADDRESSES_REQUEST';
export const ORDER_ADDRESSES_FAIL ='ORDER_ADDRESSES_FAIL';

