export const ORDER_DETAILS_SUCCESS ='ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_REQUEST ='ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_FAIL ='ORDER_DETAILS_FAIL';


// actionTypes.js
export const MAKE_ORDER_REQUEST = 'MAKE_ORDER_REQUEST';
export const MAKE_ORDER_SUCCESS = 'MAKE_ORDER_SUCCESS';
export const MAKE_ORDER_FAILURE = 'MAKE_ORDER_FAILURE';
