export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

// actionTypes.js
export const MAKE_ORDER_REQUEST = "MAKE_ORDER_REQUEST";
export const MAKE_ORDER_SUCCESS = "MAKE_ORDER_SUCCESS";
export const MAKE_ORDER_FAILURE = "MAKE_ORDER_FAILURE";

export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_CANCEL_SUCCESS = "ORDER_CANCEL_SUCCESS";
export const ORDER_CANCEL_REQUEST = "ORDER_CANCEL_REQUEST";
export const ORDER_CANCEL_FAIL = "ORDER_CANCEL_FAIL";

// milestone3

export const TOTAL_SALES_MONTH_REQUEST = "TOTAL_SALES_MONTH_REQUEST";
export const TOTAL_SALES_MONTH_SUCCESS = "TOTAL_SALES_MONTH_SUCCESS";
export const TOTAL_SALES_MONTH_FAIL = "TOTAL_SALES_MONTH_FAIL";

export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST";
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_FAIL = "GET_ALL_ORDERS_FAIL";

export const GET_TOTAL_ORDER_COUNT_REQUEST = "GET_TOTAL_ORDER_COUNT_REQUEST";
export const GET_TOTAL_ORDER_COUNT_SUCCESS = "GET_TOTAL_ORDER_COUNT_SUCCESS";
export const GET_TOTAL_ORDER_COUNT_FAIL = "GET_TOTAL_ORDER_COUNT_FAIL";

export const GET_TOTAL_SALES_REQUEST = "GET_TOTAL_SALES_REQUEST";
export const GET_TOTAL_SALES_SUCCESS = "GET_TOTAL_SALES_SUCCESS";
export const GET_TOTAL_SALES_FAIL = "GET_TOTAL_SALES_FAIL";

export const GET_ORDER_PROFIT_REQUEST = "GET_ORDER_PROFIT_REQUEST";
export const GET_ORDER_PROFIT_SUCCESS = "GET_ORDER_PROFIT_SUCCESS";
export const GET_ORDER_PROFIT_FAIL = "GET_ORDER_PROFIT_FAIL";

export const GET_ORDER_PROFIT_PER_MONTH_REQUEST =
  "GET_ORDER_PROFIT_PER_MONTH_REQUEST";
export const GET_ORDER_PROFIT_PER_MONTH_SUCCESS =
  "GET_ORDER_PROFIT_PER_MONTH_SUCCESS";
export const GET_ORDER_PROFIT_PER_MONTH_FAIL =
  "GET_ORDER_PROFIT_PER_MONTH_FAIL";

export const GET_ORDER_EXPENSES_REQUEST = "GET_ORDER_EXPENSES_REQUEST";
export const GET_ORDER_EXPENSES_SUCCESS = "GET_ORDER_EXPENSES_SUCCESS";
export const GET_ORDER_EXPENSES_FAIL = "GET_ORDER_EXPENSES_FAIL";

export const GET_ORDER_EXPENSES_PER_MONTH_REQUEST =
  "GET_ORDER_EXPENSES_PER_MONTH_REQUEST";
export const GET_ORDER_EXPENSES_PER_MONTH_SUCCESS =
  "GET_ORDER_EXPENSES_PER_MONTH_SUCCESS";
export const GET_ORDER_EXPENSES_PER_MONTH_FAIL =
  "GET_ORDER_EXPENSES_PER_MONTH_FAIL";

export const FILTERED_ORDERS_REQUEST = "FILTERED_ORDERS_REQUEST";
export const FILTERED_ORDERS_SUCCESS = "FILTERED_ORDERS_SUCCESS";
export const FILTERED_ORDERS_FAIL = "FILTERED_ORDERS_FAIL";
