export const VIEW_PATIENTS_REQUEST = 'VIEW_PATIENTS_REQUEST';
export const VIEW_PATIENTS_SUCCESS = 'VIEW_PATIENTS_SUCCESS';
export const VIEW_PATIENTS_FAIL = 'VIEW_PATIENTS_FAIL';
export const VIEW_PATIENT_REQUEST = 'VIEW_PATIENT_REQUEST';
export const VIEW_PATIENT_SUCCESS = 'VIEW_PATIENT_SUCCESS';
export const VIEW_PATIENT_FAIL = 'VIEW_PATIENT_FAIL';
