// GET_PHARMACISTS_REQUEST,
// GET_PHARMACISTS_SUCCESS,
// GET_PHARMACISTS_FAIL,
// GET_PHARMACIST_REQUEST,
// GET_PHARMACIST_SUCCESS,
// GET_PHARMACIST_FAIL
export const GET_PHARMACIST_REQUEST = 'GET_PHARMACIST_REQUEST';
export const GET_PHARMACIST_SUCCESS = 'GET_PHARMACIST_SUCCESS';
export const GET_PHARMACIST_FAIL = 'GET_PHARMACIST_FAIL';
export const GET_PHARMACISTS_REQUEST = 'GET_PHARMACISTS_REQUEST';
export const GET_PHARMACISTS_SUCCESS = 'GET_PHARMACISTS_SUCCESS';
export const GET_PHARMACISTS_FAIL = 'GET_PHARMACISTS_FAIL';
