// GET_PHARMACISTS_REQUEST,
// GET_PHARMACISTS_SUCCESS,
// GET_PHARMACISTS_FAIL,
// GET_PHARMACIST_REQUEST,
// GET_PHARMACIST_SUCCESS,
// GET_PHARMACIST_FAIL
export const GET_PHARMACIST_REQUEST = "GET_PHARMACIST_REQUEST";
export const GET_PHARMACIST_SUCCESS = "GET_PHARMACIST_SUCCESS";
export const GET_PHARMACIST_FAIL = "GET_PHARMACIST_FAIL";
export const GET_PHARMACISTS_REQUEST = "GET_PHARMACISTS_REQUEST";
export const GET_PHARMACISTS_SUCCESS = "GET_PHARMACISTS_SUCCESS";
export const GET_PHARMACISTS_FAIL = "GET_PHARMACISTS_FAIL";
export const PHARMACIST_ACCEPTED_REQUEST = "PHARMACIST_ACCEPTED_REQUEST";
export const PHARMACIST_ACCEPTED_SUCCESS = "PHARMACIST_ACCEPTED_SUCCESS";
export const PHARMACIST_ACCEPTED_FAIL = "PHARMACIST_ACCEPTED_FAIL";

export const PHARMACIST_DOWNLOAD_DOCS_REQUEST =
  "PHARMACIST_DOWNLOAD_DOCS_REQUEST";
export const PHARMACIST_DOWNLOAD_DOCS_SUCCESS =
  "PHARMACIST_DOWNLOAD_DOCS_SUCCESS";
export const PHARMACIST_DOWNLOAD_DOCS_FAIL = "PHARMACIST_DOWNLOAD_DOCS_FAIL";
