export const PHARMACIST_GET_ALL_REQUEST = 'PHARMACIST_GET_ALL_REQUEST'
export const PHARMACIST_GET_ALL_SUCCESS = 'PHARMACIST_GET_ALL_SUCCESS'
export const PHARMACIST_GET_ALL_FAIL = 'PHARMACIST_GET_ALL_FAIL'

export const PHARMACIST_GET_BY_ID_REQUEST = 'PHARMACIST_GET_BY_ID_REQUEST'
export const PHARMACIST_GET_BY_ID_SUCCESS = 'PHARMACIST_GET_BY_ID_SUCCESS'
export const PHARMACIST_GET_BY_ID_FAIL = 'PHARMACIST_GET_BY_ID_FAIL'

