export const ORDER_DETAILS_SUCCESS ='ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_REQUEST ='ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_FAIL ='ORDER_DETAILS_FAIL';


// actionTypes.js
export const MAKE_ORDER_REQUEST = 'MAKE_ORDER_REQUEST';
export const MAKE_ORDER_SUCCESS = 'MAKE_ORDER_SUCCESS';
export const MAKE_ORDER_FAILURE = 'MAKE_ORDER_FAILURE';

export const ORDER_LIST_SUCCESS ='ORDER_LIST_SUCCESS';
export const ORDER_LIST_REQUEST ='ORDER_LIST_REQUEST';
export const ORDER_LIST_FAIL ='ORDER_LIST_FAIL';

export const ORDER_CANCEL_SUCCESS ='ORDER_CANCEL_SUCCESS';
export const ORDER_CANCEL_REQUEST ='ORDER_CANCEL_REQUEST';
export const ORDER_CANCEL_FAIL ='ORDER_CANCEL_FAIL';