export const VIEW_PATIENTS_REQUEST = 'VIEW_PATIENTS_REQUEST';
export const VIEW_PATIENTS_SUCCESS = 'VIEW_PATIENTS_SUCCESS';
export const VIEW_PATIENTS_FAIL = 'VIEW_PATIENTS_FAIL';
export const VIEW_PATIENT_REQUEST = 'VIEW_PATIENT_REQUEST';
export const VIEW_PATIENT_SUCCESS = 'VIEW_PATIENT_SUCCESS';
export const VIEW_PATIENT_FAIL = 'VIEW_PATIENT_FAIL';


export const VIEW_MY_DETAILS_SUCCESS="VIEW_MY_DETAILS_SUCCESS";
export const VIEW_MY_DETAILS_REQUEST="VIEW_MY_DETAILS_REQUEST";
export const VIEW_MY_DETAILS_FAIL="VIEW_MY_DETAILS_FAIL";


export const ADD_ADDRESSES_FAIL ='ADD_ADDRESSES_FAIL';
export const ADD_ADDRESSES_REQUEST ='ADD_ADDRESSES_REQUEST';
export const ADD_ADDRESSES_SUCCESS='ADD_ADDRESSES_SUCCESS';
