// socketConstants.js
export const SOCKET_CONNECT = "SOCKET_CONNECT";
export const SOCKET_DISCONNECT = "SOCKET_DISCONNECT";
export const NEW_MESSAGE = "NEW_MESSAGE";



export const CROSS_SOCKET_CONNECT = "CROSS_SOCKET_CONNECT";
export const CROSS_SOCKET_DISCONNECT = "CROSS_SOCKET_DISCONNECT";
export const CROSS_NEW_MESSAGE = "CROSS_NEW_MESSAGE";
