export const USER_REMOVE_SUCCESS = 'USER_REMOVE_SUCCESS';
export const USER_REMOVE_REQUEST = 'USER_REMOVE_REQUEST';
export const USER_REMOVE_FAIL = 'USER_REMOVE_FAIL';

export const USERS_GET_REQUEST = "USERS_GET_REQUEST"
export const USERS_GET_SUCCESS = "USERS_GET_SUCCESS"
export const USERS_GET_FAIL = "USERS_GET_FAIL"