import { Inter } from "next/font/google";
import { ReduxProvider } from "../redux/provider";
import AdminNavbar from "../../../components/AdminNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <div className={`global-text ${inter.className}`}>
        <AdminNavbar />
        <div className="p-2 m-5">
        <ReduxProvider> {children} </ReduxProvider>
        </div>
      </div>
  );
}
