"use client";
import { Inter } from "next/font/google";
import { ReduxProvider } from "../redux/provider";
import PatientNavbar from "../../../components/PatientNavbar";
import Sidebar from "../../../components/PatientSidebar";
import "./patient.css";
import { FaComment } from "react-icons/fa";
import { useState } from "react";
import ChatModal from "../../../components/chatModal";
import { initSocket } from "../redux/actions/socketActions";
import { useDispatch, useSelector } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [showChatPanel, setShowChatPanel] = useState(false);

  const { connected } = useSelector((state) => state.socketReducer);
  const dispatch = useDispatch();

  const handleChatIconClick = () => {
    setShowChatPanel(true);

    dispatch(initSocket());
  };

  const handleCloseChatPanel = () => {
    setShowChatPanel(false);
  };

  return (
    <div className={`global-text ${inter.className}`}>
      <PatientNavbar />

      <ReduxProvider> {children} </ReduxProvider>

      <div
        className="chat-icon"
        onClick={handleChatIconClick}
        data-tip="Get Help from one of our pharmacists"
      >
        <FaComment />
      </div>

      {/* Chat Panel */}
      <ChatModal isOpen={showChatPanel} handleClose={handleCloseChatPanel} />
    </div>
  );
}
