import { Inter } from "next/font/google";
import { ReduxProvider } from "../redux/provider";
import PatientNavbar from "../../../components/PatientNavbar";
import Sidebar from "../../../components/PatientSidebar";
import "./patient.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className={`global-text ${inter.className}`}>
      <PatientNavbar />

      <ReduxProvider> {children} </ReduxProvider>
    </div>
  );
}
